environment:

  matrix:
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python38-x64"
    - PYTHON: "C:\\Python39-x64"


install:
  - "%PYTHON%\\python.exe -m pip install wheel ."

build: off

test_script:
  - "%PYTHON%\\python.exe test.py"

after_test:
  - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*
